#pragma once

#include <string>
#include <filesystem>
#include "fenix/utils/std_types.hh"
#include <glad/glad.h>

namespace fenix {

    class Texture2D
    {
    public:
        /// Allocates memory in the GPU to store a texture of the specified dimensions.
        Texture2D(u32 width, u32 height);

        /// Loads a texture from memory to the GPU.
        Texture2D(const std::filesystem::path& path);

        /// Deletes this texture from the OpenGL context. It's ID can be used again by
        /// new generated textures.
        ~Texture2D();

        /// Binds the texture to the specified texture unit.
        void Bind(u32 slot = 0) const;

        /// Fills the memory region of the texture with the given data.
        void SetData(void* data, u32 size);

        /// Returns the texture width in pixels.
        u32 GetWidth() const { return m_Width; }

        /// Returns the texture height in pixels.
        u32 GetHeight() const { return m_Height; }

        /// Returns the texture identifier generated by OpenGL.
        u32 GetRendererID() const { return m_RendererID; }

        bool operator==(const Texture2D& other) const { return m_RendererID == other.m_RendererID; }

    private:
        std::filesystem::path m_Path;
        u32 m_Width;
        u32 m_Height;
        u32 m_RendererID;
        GLenum m_InternalFormat;
        GLenum m_DataFormat;
    };

} // namespace fenix
